### ISSUE TITLE
Technique used for getting keypoints of garment and person

### ISSUE THREAD

**Issue by Teja414** [fashn-AI/tryondiffusion#3]

**Comment by Teja414** [comment]
can you give the techniques used for finding the keypoints of garment and person

**Comment by danbochman** [comment]
Hi @Teja414 

The (18, 2) keypoints format fits the [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) keypoints detector.

**Comment by Teja414** [comment]
is open pose keypoints detector used for both garment and person keypoints or just for person keypoints

**Comment by danbochman** [comment]
My friend, please read the paper, it will answer most of your questions. After you give it a proper read, you are welcome to ask me questions about parts you did not understand.
