### ISSUE TITLE
strange error after simple experiments

### ISSUE THREAD

**Issue by concrete13377** [fashn-AI/tryondiffusion#6]
![image](https://github.com/fashn-AI/tryondiffusion/assets/32034827/72954884-11eb-4914-b971-a7897d7fa1f2)

I have no idea what can it be, also sometimes it gets segmentation faults, which I dont understand as well

**Comment by danbochman** [comment]
It is really hard to understand just from this error without the context what could be the issue.

**Comment by concrete13377** [comment]
looks like something wrong with my env, I'll try rebuild it later
