### ISSUE TITLE
Environment doubt

### ISSUE THREAD

**Issue by karthik1coder** [fashn-AI/tryondiffusion#8]
Hey,can you send me version of all packages and including python version?
Thank you

**Comment by danbochman** [comment]
Hi,

You should be able to run this with the most up-to-date versions. More important probably is to have Python 3.10, CUDA 11.8.

ema-pytorch                  0.4.2
torch                        2.2.0
torchvision                  0.17.0
transformers                 4.37.2
accelerate                   0.26.1

**Comment by karthik1coder** [comment]
Can you give some reference to coding conditioned self,cross attentions?

**Comment by danbochman** [comment]
I don't understand what you mean by reference to coding, you mean to papers?

**Comment by karthik1coder** [comment]
Yes papers or any videos please

**Comment by danbochman** [comment]
Sorry, the only way I know how to learn this is to look at other repositories and see how they are doing it...
I can recommend this repository - https://github.com/crowsonkb/k-diffusion/blob/master/k_diffusion/layers.py

**Comment by karthik1coder** [comment]
Thank you
