### ISSUE TITLE
How much memory is required to run code test_tryon_image and can it be used in Colab? I am running the example in Google Colab, but it shows that there is not enough RAM memory. Is there a way to optimize it or is there a Colab example available

### ISSUE THREAD

**Issue by libai-lab** [fashn-AI/tryondiffusion#9]
How much memory is required to run code test_tryon_image and can it be used in Colab? I am running the example in Google Colab, but it shows that there is not enough RAM memory. Is there a way to optimize it or is there a Colab example available

**Comment by danbochman** [comment]
Just the model weights for the (cascaded) model are around 11GB so it makes sense that with the standard Colab machine (12 GB RAM) it won't be enough. 
You should have around 16GB RAM and 24GB GPU memory to run this model.
